version: '3.3'
services:
    app:
        build: .
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./:/app:delegated
        ports:
            - 8000:80
        depends_on:
            - db
            - cache
    db:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: yii2gallery
            MYSQL_USER: yii2
            MYSQL_PASSWORD: yii2
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - 3306:3306
    cache:
          image: redis:latest
          restart: always
          volumes:
            - cache_data:/data
          ports:
            - 6379:6379
volumes:
    db_data:
    cache_data:
